### ISSUE TITLE
Error: This browser does not support webGL. Try using the canvas renderer

### ISSUE THREAD

**Issue by noteon** [fireball-x/editor-framework-app#2]
When I launch the app under windows 7 and click  menu -> Packages->Grid->Open. I got the following error.

<span class="style-scope editor-console">Error: This browser does not support webGL. Try using the canvas renderer
    at i._createContext (app://bower_components/pixi/bin/pixi.min.js:5:24276)
    at new i (app://bower_components/pixi/bin/pixi.min.js:5:23576)
    at pixi-grid.Editor.registerWidget.ready (app://builtin/pixi-grid/widget/pixi-grid.js:82:25)
    at pixi-grid.Polymer.Base._addFeature._invokeBehavior (app://bower_components/polymer/polymer-micro.html:281:4)
    at pixi-grid.Polymer.Base._addFeature._doBehavior (app://bower_components/polymer/polymer-micro.html:276:6)
    at pixi-grid.Polymer.Base._addFeature._readySelf (app://bower_components/polymer/polymer-mini.html:76:6)
    at pixi-grid.Polymer.Base._addFeature._ready (app://bower_components/polymer/polymer-mini.html:63:6)
    at grid-view.Polymer.Base._addFeature._readyClients (app://bower_components/polymer/polymer-mini.html:69:3)
    at grid-view.Polymer.Base._addFeature._ready (app://bower_components/polymer/polymer-mini.html:61:6)
    at grid-view.Polymer.Base._addFeature._tryReady (app://bower_components/polymer/polymer-mini.html:52:6)</span>

**Comment by noteon** [comment]
My Electron version is v0.28.1

**Comment by jwu** [comment]
I use electron v0.28.3, and can not reproduce this problem. I will try Windows 7 later to confirm this.

**Comment by jwu** [comment]
Aha, are u trying to use editor-framework from the editor-framework-app ?? This repo is broken, and I haven't fix it, please try https://github.com/fireball-x/editor-framework and follow the readme to start it there.

**Comment by noteon** [comment]
Is there any workable sample for editor-framework? I need some boilerplate to start.

**Comment by jwu** [comment]
You can check https://github.com/fireball-packages/package-examples , if you start the editor-framework demo.sh, it already include it and just run the examples from the main menu.

You can also check https://github.com/fireball-x/fireball which is deeply working with editor-framework. The packages https://github.com/fireball-packages includes all the packages we are developing right now for both editor-framework and fireball
